name: PIPELINE
on: 
   push: 
      paths-ignore:
         - 'README.md'
      branches:
         - main
   pull_request:
      paths:
        - '**/*'
        - '!.github/workflows/**'

env:
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
   REPO_NAME: ${{ secrets.REPO_NAME }}
   
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: checkout repo
       uses: actions/checkout@main   

     - name: Login to Amazon ECR
       id: login-ecr
       uses: docker/login-action@v3
       with:
         registry: ${{ env.ECR_REGISTRY }}
         username: ${{ env.AWS_ACCESS_KEY_ID }}
         password: ${{ env.AWS_SECRET_ACCESS_KEY }}

     - name: Build, tag, and push the image to Amazon ECR
       id: build-image

       run: |
         cd app
         export AWS_REGION=us-east-1
         docker build . -t ${{ secrets.REPO_NAME }}:${{ secrets.CODEBUILD_RESOLVED_SOURCE_VERSION }} --build-arg AWS_REGION=${{ secrets.AWS_REGION }} -f Dockerfile
         docker tag ${{ secrets.REPO_NAME }}:${{ secrets.CODEBUILD_RESOLVED_SOURCE_VERSION }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.REPO_NAME }}:${{ secrets.CODEBUILD_RESOLVED_SOURCE_VERSION }}
         docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.REPO_NAME }}:${{ secrets.CODEBUILD_RESOLVED_SOURCE_VERSION }}

         cd ..
         terraform init
         ssh-keygen -m PEM -f panw -N ""
         terraform apply --auto-approve